-- Estrutura inicial do microsserviço pedidos (somente DDL)

CREATE TABLE cliente (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(150) NOT NULL,
    documento   VARCHAR(14)  NOT NULL,
    email       VARCHAR(150),
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    versao      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_cliente_documento UNIQUE (documento)
);

CREATE TABLE produto (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(30)   NOT NULL,
    descricao   VARCHAR(200)  NOT NULL,
    preco       NUMERIC(12,2) NOT NULL CHECK (preco >= 0),
    ativo       BOOLEAN       NOT NULL DEFAULT TRUE,
    criado_em   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    versao      BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_produto_codigo UNIQUE (codigo)
);

CREATE TABLE pedido (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      BIGINT        NOT NULL REFERENCES cliente (id),
    status          VARCHAR(20)   NOT NULL,
    total           NUMERIC(14,2) NOT NULL DEFAULT 0,
    observacao      VARCHAR(500),
    criado_em       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    atualizado_em   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    versao          BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_pedido_status CHECK (status IN ('ABERTO', 'CONFIRMADO', 'CANCELADO'))
);
CREATE INDEX ix_pedido_cliente ON pedido (cliente_id);
CREATE INDEX ix_pedido_status ON pedido (status);

CREATE TABLE item_pedido (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id        BIGINT        NOT NULL REFERENCES pedido (id) ON DELETE CASCADE,
    produto_id       BIGINT        NOT NULL REFERENCES produto (id),
    quantidade       INTEGER       NOT NULL CHECK (quantidade > 0),
    preco_unitario   NUMERIC(12,2) NOT NULL CHECK (preco_unitario >= 0)
);
CREATE INDEX ix_item_pedido_pedido ON item_pedido (pedido_id);
CREATE INDEX ix_item_pedido_produto ON item_pedido (produto_id);
